# tooling/src/otsafety_tooling/planning/layers.py
"""Which unresolvable layers a model card must declare before it may promote.

A LAYER WHOSE GAP CANNOT BE CLOSED IS NOT A TASK, it is a limitation that
travels with every claim the model makes. Layer 1 is the project's: the question
is about on-target biology and every observation is generated by drug
pharmacology, which no amount of engineering separates.

SO THE CARD MUST SAY SO. A score shipped without that declaration is a score
presented as causation, which is the single failure this architecture exists to
prevent.
"""

from __future__ import annotations

from collections.abc import Iterable

from otsafety_tooling.contracts.architecture import Architecture


def unresolvable(architecture: Architecture) -> tuple[int, ...]:
    """Every layer whose gap no engineering closes."""
    return tuple(int(layer.n) for layer in architecture.layers if not layer.resolvable)


def undeclared(architecture: Architecture, declared: Iterable[int]) -> list[int]:
    """The unresolvable layers a card has not declared: empty, or a refusal."""
    seen = set(declared)
    return [n for n in unresolvable(architecture) if n not in seen]
