# tooling/tests/test_model_card_contract.py
"""The model card is a contract, not documentation written afterwards (E.36).

THE TRAINED MODEL IS NOT THE SCIENTIFIC RESULT. It must travel with what is
needed to interpret its claims: an identity card, an evidence report, and a
statement of what it may not legitimately claim. Three steps already depend on
one -- 9.15 writes it, 9.20 refuses it, E.35 feeds it -- and nothing said what
it must contain.

STRUCTURAL PRESENCE IS NOT SUBSTANTIVE CONTENT. 2026 governance practice is
blunt: a card reporting aggregate accuracy with no subgroup breakdown and an
undisclosed test set is technically a card and gives none of the protection the
format exists for. So the schema refuses an aggregate-only card, refuses
boilerplate, and refuses a card whose claim its own evidence does not support.

THE LIMITATION THIS PROJECT CANNOT RESOLVE IS LAYER 1'S. On-target biology is
conflated with drug pharmacology: the project asks about the first and every
piece of evidence is generated by the second. That is unresolvable, so it is
declared rather than fixed, and a card without it is refused.
"""

from __future__ import annotations

import pytest
from pydantic import ValidationError

pytestmark = pytest.mark.requirement("E.36")


def _card(**overrides: object) -> object:
    """A card that validates, so each test can break exactly one thing."""
    from otsafety_tooling.contracts.model_card import ModelCard

    base: dict[str, object] = {
        "contract": "model-card/v1",
        "model": {
            "name": "rgcn-degree-offset",
            "rung": "relation-aware-gnn",
            "question": "Q3",
            "commit": "0" * 40,
            "release_pin": "opentargets-26.03",
            "seeds": (11, 22, 33, 44, 55),
        },
        "intended_use": (
            "Prioritising protein targets for safety review at the organ-class level, as one "
            "input among several, where a human reviews the ranked list before any decision."
        ),
        "out_of_scope_use": (
            "Not a compound-level toxicity prediction, not a clinical decision aid, and not "
            "evidence that modulating a target causes an endpoint in a patient."
        ),
        "slices": (
            {"name": "degree decile 1", "kind": "degree", "n": 412, "average_precision": 0.31},
            {"name": "degree decile 10", "kind": "degree", "n": 408, "average_precision": 0.62},
        ),
        "contrasts": (
            {
                "against": "degree-only-null",
                "question": "Q1",
                "ap_lift": 0.04,
                "ci_low": 0.01,
                "ci_high": 0.07,
            },
        ),
        "limitations": (
            {
                "layer": 1,
                "kind": "unresolvable",
                "statement": (
                    "On-target biology is conflated with drug pharmacology: the question is "
                    "about the target, and every observation is generated by a compound."
                ),
            },
        ),
        "verdict": "promote",
        "attestation": {
            "payloadType": "application/vnd.in-toto+json",
            "payload": "eyJfdHlwZSI6ICJodHRwczovL2luLXRvdG8uaW8vU3RhdGVtZW50L3YxIn0=",
            "signatures": (
                {
                    "sig": "MEUCIQD" + "A" * 57,
                    "cert": "-----BEGIN CERTIFICATE-----\\nMIIC\\n-----END CERTIFICATE-----",
                },
            ),
            "transparency": {
                "log": "rekor.sigstore.dev",
                "entry": 148392017,
                "logged_at": "2026-09-25T10:00:00Z",
            },
        },
    }
    base.update(overrides)
    return ModelCard.model_validate(base)


def test_a_card_that_states_everything_validates() -> None:
    """The positive control: without it, every refusal below proves nothing."""
    assert _card()


def test_a_card_with_one_slice_is_refused() -> None:
    """An aggregate number hides the degree confound this project exists to find."""
    with pytest.raises(ValidationError):
        _card(slices=({"name": "overall", "kind": "degree", "n": 820, "average_precision": 0.47},))


def test_a_card_with_no_layer_one_limitation_is_refused() -> None:
    """The unresolvable gap is declared, or the card is not this project's."""
    with pytest.raises(ValidationError):
        _card(
            limitations=(
                {
                    "layer": 8,
                    "kind": "known",
                    "statement": (
                        "Degree explains part of the score, and the offset head absorbs it."
                    ),
                },
            )
        )


def test_boilerplate_is_refused() -> None:
    """A one-line intended use is the failure mode the length floor exists for."""
    with pytest.raises(ValidationError):
        _card(intended_use="Predicts target safety.")


def test_a_promotion_with_no_contrast_is_refused() -> None:
    """A verdict is a claim, and a claim with no contrast has no evidence."""
    with pytest.raises(ValidationError):
        _card(contrasts=())


def test_a_rejection_needs_no_contrast() -> None:
    """A negative result is a real finding: refusing to promote claims nothing."""
    assert _card(verdict="reject", contrasts=())
