# tooling/tests/test_limitation_is_not_a_formality.py
"""Declaring a limitation means declaring what it is (E.39).

A CARD COULD NAME LAYER 1 AND DENY ITS NATURE. Measured: a limitation reading
layer 1, kind known, statement "we reviewed layer one and found the pipeline
handles it adequately" validated and passed. The rule required a number to
appear, which is a formality, not a declaration.

A STORED BOOLEAN WOULD NOT HAVE HELPED. An is_acknowledged flag is set by the
same pipeline that must acknowledge; 2026 practice calls that rubber stamping
and observes that a test asserting the boolean is stored asserts nothing --
what matters is whether the write fails. The content is the control.

SO THE CARD IS CHECKED AGAINST THE ARCHITECTURE. Layer 1 is the only layer whose
resolvable is false, and a card that declares it must declare it as
unresolvable. A pipeline cannot reclassify the conflation by typing a different
word, because the word is compared with the document the sheet, the site and the
README all read.
"""

from __future__ import annotations

import pytest
from pydantic import ValidationError

pytestmark = pytest.mark.requirement("E.39")

ATTESTATION: dict[str, object] = {
    "payloadType": "application/vnd.in-toto+json",
    "payload": "eyJfdHlwZSI6ICJ4In0=",
    "signatures": ({"sig": "M" * 64, "cert": "-----BEGIN CERTIFICATE-----x"},),
    "transparency": {
        "log": "rekor.sigstore.dev",
        "entry": 1,
        "logged_at": "2026-09-25T10:00:00Z",
    },
}

HONEST = {
    "layer": 1,
    "kind": "unresolvable",
    "statement": (
        "On-target biology is conflated with drug pharmacology: the question is about the "
        "target, and every observation is generated by a compound."
    ),
}


def _card(**overrides: object) -> object:
    from otsafety_tooling.contracts.model_card import ModelCard

    base: dict[str, object] = {
        "model": {
            "name": "rgcn",
            "rung": "relation-aware-gnn",
            "question": "Q3",
            "commit": "0" * 40,
            "release_pin": "opentargets-26.03",
            "seeds": (1, 2, 3, 4, 5),
        },
        "intended_use": (
            "Prioritising protein targets for safety review at the organ-class level, as one "
            "input among several, where a human reviews the ranked list before any decision."
        ),
        "out_of_scope_use": (
            "Not a compound-level toxicity prediction, not a clinical decision aid, and not "
            "evidence that modulating a target causes an endpoint in a patient."
        ),
        "slices": (
            {"name": "decile 1", "kind": "degree", "n": 412, "average_precision": 0.31},
            {"name": "decile 10", "kind": "degree", "n": 408, "average_precision": 0.62},
        ),
        "contrasts": (
            {
                "against": "degree-only-null",
                "question": "Q1",
                "ap_lift": 0.04,
                "ci_low": 0.01,
                "ci_high": 0.07,
            },
        ),
        "limitations": (HONEST,),
        "verdict": "promote",
        "attestation": ATTESTATION,
    }
    base.update(overrides)
    return ModelCard.model_validate(base)


def test_an_honest_card_validates() -> None:
    """The positive control."""
    assert _card()


def test_calling_the_unresolvable_gap_known_is_refused() -> None:
    """The measured hole: a formality accepted a reclassification."""
    with pytest.raises(ValidationError):
        _card(limitations=({**HONEST, "kind": "known"},))


def test_calling_it_untested_is_refused_too() -> None:
    """Untested says the work has not been done; this work cannot be done."""
    with pytest.raises(ValidationError):
        _card(limitations=({**HONEST, "kind": "untested"},))


def test_a_resolvable_layer_may_be_declared_any_way_it_likes() -> None:
    """The rule binds the unresolvable layers, not every mention of a layer."""
    assert _card(
        limitations=(
            HONEST,
            {
                "layer": 2,
                "kind": "known",
                "statement": (
                    "Study attention shapes which truths became evidence, and the degree null "
                    "is what keeps that from being read as biology."
                ),
            },
        )
    )


def test_the_architecture_is_what_decides() -> None:
    """Not a list in this file: the document every renderer reads."""
    from otsafety_tooling.contracts.architecture import Architecture
    from otsafety_tooling.contracts.files import read_yaml
    from otsafety_tooling.paths import REPO_ROOT
    from otsafety_tooling.planning.layers import unresolvable

    architecture = read_yaml(REPO_ROOT / "context" / "architecture.yaml", Architecture)
    assert unresolvable(architecture) == (1,), (
        "the architecture no longer says layer 1 alone is unresolvable"
    )
