# tooling/tests/test_layer_semantics.py
"""A layer's semantics are typed, not buried in prose (E.38).

THE NINE LAYERS WERE MODELLED AND GATE-WALKED, AND STILL UNREADABLE. Layer 1
carries the sentence "On-target biology is conflated with drug pharmacology.
The project asks about the first; all evidence is generated by the second." --
which no program can act on. Nothing typed said what the layer asks about, what
generates its evidence, or that no engineering closes the gap between them.

NINE CLASSES WOULD HAVE BEEN THE WRONG SHAPE. The layers have identical fields
and differ only in values, and 8.5 exists precisely because those values were
once typed in Python and a second copy diverged unnoticed. 2026 practice
reserves a class per variant for genuinely different shapes; here the strength
comes from typed FIELDS on one model, enforced in the contract the sheet, the
site and the README already read.

RESOLVABLE IS THE FIELD THAT MATTERS. A layer whose gap can be closed is work
not yet done; one whose gap cannot is a limitation that must travel with every
claim the model makes. Layer 1 is the second kind, and the card refuses to
validate without declaring it.
"""

from __future__ import annotations

import pytest
from pydantic import ValidationError

from otsafety_tooling.contracts.architecture import Architecture, Layer
from otsafety_tooling.contracts.files import read_yaml
from otsafety_tooling.paths import REPO_ROOT

pytestmark = pytest.mark.requirement("E.38")

SOURCE = REPO_ROOT / "context" / "architecture.yaml"


def _architecture() -> Architecture:
    return read_yaml(SOURCE, Architecture)


def test_every_layer_states_what_it_asks_about() -> None:
    """The subject of the question, as a term rather than a sentence."""
    silent = [layer.n for layer in _architecture().layers if not layer.asks]
    assert silent == [], f"layers stating no subject: {silent}"


def test_every_layer_states_what_generates_its_evidence() -> None:
    """The gap at layer 1 is exactly the distance between these two."""
    silent = [layer.n for layer in _architecture().layers if not layer.evidence_from]
    assert silent == [], f"layers stating no evidence source: {silent}"


def test_every_layer_says_whether_its_gap_can_be_closed() -> None:
    """Work not yet done and a limitation that travels are different things."""
    for layer in _architecture().layers:
        assert isinstance(layer.resolvable, bool), f"layer {layer.n} does not say"


def test_layer_one_asks_about_biology_and_is_answered_by_pharmacology() -> None:
    """The unresolvable conflation, readable by a program."""
    first = next(layer for layer in _architecture().layers if layer.n == "1")
    assert first.asks == "on-target-biology"
    assert first.evidence_from == "drug-pharmacology"
    assert first.resolvable is False, "layer 1 claims its gap can be closed"


def test_a_layer_whose_subject_is_its_evidence_source_must_be_resolvable() -> None:
    """If the two agree there is no gap, so calling it unresolvable is wrong."""
    with pytest.raises(ValidationError):
        Layer(
            id="9",
            n="9",
            name="EXAMPLE",
            origin="added",
            question="Does this shape refuse what it should?",
            failure="A layer claiming an unresolvable gap between a thing and itself.",
            guard="none",
            as_code="--",
            as_data="none",
            produced_by=("9.15",),
            asks="metrics",
            evidence_from="metrics",
            resolvable=False,
        )


def test_the_card_cannot_promote_while_an_unresolvable_layer_is_undeclared() -> None:
    """The refusal this exists for: a score shipped as causation."""
    from otsafety_tooling.planning.layers import undeclared

    architecture = _architecture()
    assert undeclared(architecture, declared=()) != [], "a card declaring nothing passes"
    assert undeclared(architecture, declared=(1,)) == [], (
        "a card declaring layer 1 is still refused"
    )
