# tooling/src/otsafety_tooling/readme.py
"""The repository's front page, generated from the plan and the toolchain.

A HAND-WRITTEN README IS THE FILE G.28 REFUSES: prose beside the code,
describing it from outside, with nothing checking the two against each other.
This one is checked -- the drift gate regenerates it and compares, as it does
for the Zod and the site's content -- so the ban narrows to what is written
rather than lifting.

EVERY FIGURE IS OBSERVED. The step counts come from the same collection the
architecture sheet reads, the tools from toolchain.json, the contracts from
what the export produced. Nothing here is typed, for the reason the sheet's
status is not: a number written once is wrong from the next commit onward.
"""

from __future__ import annotations

from pathlib import Path

from pydantic import BaseModel, ConfigDict

from otsafety_tooling.contracts.architecture import Architecture, Layer
from otsafety_tooling.contracts.files import read_json, read_yaml
from otsafety_tooling.contracts.toolchain import Toolchain
from otsafety_tooling.paths import REPO_ROOT

TARGET = Path("README.md")

QUESTION = (
    "Do the typed **relationships** in a public, open-source biomedical knowledge graph carry "
    "information that predicts drug-safety endpoints for protein targets -- over and above what "
    "is predictable from the graph's bare connectivity statistics, and from target-level "
    "features that require no graph at all?"
)


class ReadmeWritten(BaseModel):
    """What the generator wrote, and how much of it."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    path: str
    bytes: int


def _tools(root: Path) -> list[str]:
    """Every pinned executable, with the version the toolchain declares."""
    toolchain = read_json(root / "toolchain.json", Toolchain)
    return [f"{name} {getattr(toolchain, name).version}" for name in sorted(toolchain.binaries)]


def _layers(root: Path) -> tuple[Layer, ...]:
    """The nine layers, from the document the sheet and the site also read."""
    return read_yaml(root / "context" / "architecture.yaml", Architecture).layers


def _contracts(root: Path) -> int:
    return len(list((root / "contracts" / "json").glob("*.schema.json")))


def render(root: Path = REPO_ROOT) -> str:
    """The README, from what the repository holds that does not move.

    NO FIGURE ITS OWN COMMIT CHANGES. The first version stated completed steps,
    test functions, merged pull requests and seven thread percentages, and the
    drift gate refused three pushes in one day -- each time because the commit
    completed a step the page counts. Regenerating clears that until the next
    commit, which is a treadmill rather than a fix.

    LIVE SIGNALS, NOT STALE NUMBERS, is the settled 2026 answer: counts come out
    of a README in favour of something that resolves when a reader looks, after
    the same numbers were bumped across four pull requests and conflicted on
    every rebase. Here that is the workflow badge, which GitHub renders from the
    current run, and the command that measures.

    WHAT STAYS IS WHAT HOLDS: the question, the confound being controlled for,
    how the work is gated, the data, and the stack pinned by digest.
    """
    tools = ", ".join(_tools(root))
    layers = "\n".join(
        f"| {layer.n} | {layer.name} | {layer.failure.split('.')[0]}. | {layer.as_data} |"
        for layer in _layers(root)
    )
    return f"""# README.md
<!-- GENERATED by otsafety_tooling.readme. Do not edit: run mise run readme. -->

# otsafety-gnn

[![Tooling](https://github.com/ltphongssvn/otsafety-gnn/actions/workflows/test-tooling.yml/badge.svg)](https://github.com/ltphongssvn/otsafety-gnn/actions/workflows/test-tooling.yml)
[![Site](https://github.com/ltphongssvn/otsafety-gnn/actions/workflows/test-site.yml/badge.svg)](https://github.com/ltphongssvn/otsafety-gnn/actions/workflows/test-site.yml)

{QUESTION}

The deliverable is a defensible answer plus its evidence, **in either
direction**. A negative result -- that the knowledge graph encodes study
attention rather than safety biology -- is a real finding this project is built
to report.

## What is being controlled for

A graph model can score well on a biomedical knowledge graph by learning which
nodes are popular. Targets that have been studied more carry more edges and more
recorded adverse events, so **degree predicts the label** before any biology is
considered. Every rung of the model ladder runs on an identical protocol against
a degree-only null, and the gate is the lift over that null rather than the raw
score.

## The chain of accountability

Nine layers, each answering one question, each leaving one record. Every layer
names the plan steps that produce its record, and a gate walks the chain: a link
pointing at a step that does not exist, or at an id never issued, fails.

| # | Layer | Failure if unguarded | The record it leaves |
|---|---|---|---|
{layers}

## How it is kept honest

Every operation is a task, every task reports a typed outcome, and ten gates run
in one pass before any push: the toolchain proved to be its pinned binaries,
lint, types, tests, the site's types and lint, policy as Rego, browser tests,
the architecture sheet rendered in a pinned image, and the Nix flake.

Each requirement carries an id issued once and never reused, the observation
that justifies it, the file that proves it, and the commits that claim it.

**Nothing here states a number that the next commit would change.** Status is
derived, not stored: `mise run plan:status` observes it, and `mise run
plan:report` prints every step in every phase -- its state, what it waits on,
what proves it, and for an open step exactly what is missing.

## Data

Open Targets, pinned by release and digest in `conf/config.yaml`. Hetionet and
PrimeKG for cross-graph replication. The endpoint hierarchy comes from EFO,
MONDO and HPO; MedDRA is licensed and is not redistributed.

## The stack

{tools}, each the vendor's artifact for macOS and Linux with its published
sha256 in `toolchain.json`, resolved through a Nix flake that asserts the
version every tool reports.

## Getting started

```
mise run setup          # the environment, from the lockfiles, frozen
mise run check          # every gate, all failures reported in one pass
mise run plan:status    # what is done, observed rather than claimed
mise run plan:report    # every step in every phase, as a one-page sheet
```
"""


def main() -> int:
    """Write the README, and report what it states."""
    from otsafety_tooling.cli import note, result

    target = REPO_ROOT / TARGET
    text = render()
    target.write_text(text, encoding="utf-8")
    note(f"wrote {TARGET}")
    return result(
        "readme",
        "success",
        "readme_written",
        f"{len(text)} bytes from the plan and the toolchain",
        ReadmeWritten(path=str(TARGET), bytes=len(text)),
    )


if __name__ == "__main__":
    raise SystemExit(main())
