# tooling/src/otsafety_tooling/readme.py
"""The repository's front page, generated from the plan and the toolchain.

A HAND-WRITTEN README IS THE FILE G.28 REFUSES: prose beside the code,
describing it from outside, with nothing checking the two against each other.
This one is checked -- the drift gate regenerates it and compares, as it does
for the Zod and the site's content -- so the ban narrows to what is written
rather than lifting.

EVERY FIGURE IS OBSERVED. The step counts come from the same collection the
architecture sheet reads, the tools from toolchain.json, the contracts from
what the export produced. Nothing here is typed, for the reason the sheet's
status is not: a number written once is wrong from the next commit onward.
"""

from __future__ import annotations

from pathlib import Path

from pydantic import BaseModel, ConfigDict

from otsafety_tooling.contracts.files import read_json
from otsafety_tooling.contracts.toolchain import Toolchain
from otsafety_tooling.paths import REPO_ROOT
from otsafety_tooling.planning.report import collect as collect_report
from otsafety_tooling.planning.sheet import collect

TARGET = Path("README.md")

QUESTION = (
    "Do the typed **relationships** in a public, open-source biomedical knowledge graph carry "
    "information that predicts drug-safety endpoints for protein targets -- over and above what "
    "is predictable from the graph's bare connectivity statistics, and from target-level "
    "features that require no graph at all?"
)


class ReadmeWritten(BaseModel):
    """What the generator wrote, and how much of it."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    path: str
    bytes: int


def _tools(root: Path) -> list[str]:
    """Every pinned executable, with the version the toolchain declares."""
    toolchain = read_json(root / "toolchain.json", Toolchain)
    return [f"{name} {getattr(toolchain, name).version}" for name in sorted(toolchain.binaries)]


def _contracts(root: Path) -> int:
    return len(list((root / "contracts" / "json").glob("*.schema.json")))


def render(root: Path = REPO_ROOT) -> str:
    """The README, from what the repository currently holds."""
    seen = collect(root)
    report = collect_report(root)
    threads = "\n".join(
        f"| {thread.id} | {thread.title} | {thread.done} of {thread.total} | {thread.percent}% |"
        for thread in seen.threads
    )
    tools = ", ".join(_tools(root))
    return f"""# README.md
<!-- GENERATED by otsafety_tooling.readme. Do not edit: run mise run readme. -->

# otsafety-gnn

{QUESTION}

The deliverable is a defensible answer plus its evidence, **in either direction**.
A negative result -- that the knowledge graph encodes study attention rather than
safety biology -- is a real finding this project is built to report.

## What is being controlled for

A graph model can score well on a biomedical knowledge graph by learning which
nodes are popular. Targets that have been studied more carry more edges and more
recorded adverse events, so **degree predicts the label** before any biology is
considered. Every rung of the model ladder is therefore run on an identical
protocol against a degree-only null, and the gate is the lift over that null
rather than the raw score.

## Status

Observed when this file was generated, never typed: **{seen.steps_done} of
{seen.steps} plan steps complete**, {report.ready} ready and {report.blocked}
blocked, across {seen.ids} issued requirement ids and {seen.requirements} matrix
rows with {report.orphans} orphan observations. {seen.test_functions} test
functions, {seen.merged_prs} merged pull requests, {seen.tasks} tasks,
{_contracts(root)} contracts.

| Thread | | Done | |
|---|---|---|---|
{threads}

## How it is kept honest

Every operation is a task, every task reports a typed outcome, and ten gates run
in one pass before any push: the toolchain proved to be its pinned binaries,
lint, types, tests, the site's types and lint, policy as Rego, browser tests,
the architecture sheet rendered in a pinned image, and the Nix flake.

Each requirement carries an id issued once and never reused, the observation
that justifies it, the file that proves it, and the commits that claim it.
Status is derived from that evidence rather than declared, and nothing here
types a number it could measure -- including this page.

## Data

Open Targets, pinned by release and digest in `conf/config.yaml`. Hetionet and
PrimeKG for cross-graph replication. The endpoint hierarchy comes from EFO,
MONDO and HPO; MedDRA is licensed and is not redistributed.

## The stack

{tools}, each the vendor's artifact for macOS and Linux with its published
sha256 in `toolchain.json`, resolved through a Nix flake that asserts the
version every tool reports.

## Getting started

```
mise run setup          # the environment, from the lockfiles, frozen
mise run check          # every gate, all failures reported in one pass
mise run plan:status    # what is done, observed rather than claimed
```
"""


def main() -> int:
    """Write the README, and report what it states."""
    from otsafety_tooling.cli import note, result

    target = REPO_ROOT / TARGET
    text = render()
    target.write_text(text, encoding="utf-8")
    note(f"wrote {TARGET}")
    return result(
        "readme",
        "success",
        "readme_written",
        f"{len(text)} bytes from the plan and the toolchain",
        ReadmeWritten(path=str(TARGET), bytes=len(text)),
    )


if __name__ == "__main__":
    raise SystemExit(main())
